#!/bin/bash

usage() {
    cat <<EOF
usage: $0 [-t target] [sconsopts...]
EOF
}

target=build/X86/gem5.opt

while getopts "ht:" optc; do
    case $optc in
        h)
            usage
            exit
            ;;
        t)
            target="$OPTARG"
            ;;
        *)
            usage >&2
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

scons "$target" -j`nproc` --ignore-style --linker=lld "$@"
